//
// File generated by rootcint at Tue Mar 10 13:54:03 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME KinFileDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "KinFileDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void THnD_KIN_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_THnD_KIN(void *p = 0);
   static void *newArray_THnD_KIN(Long_t size, void *p);
   static void delete_THnD_KIN(void *p);
   static void deleteArray_THnD_KIN(void *p);
   static void destruct_THnD_KIN(void *p);
   static Long64_t merge_THnD_KIN(void *obj, TCollection *coll,TFileMergeInfo *info);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::THnD_KIN*)
   {
      ::THnD_KIN *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::THnD_KIN >(0);
      static ::ROOT::TGenericClassInfo 
         instance("THnD_KIN", ::THnD_KIN::Class_Version(), "./KinFile.h", 32,
                  typeid(::THnD_KIN), ::ROOT::DefineBehavior(ptr, ptr),
                  &::THnD_KIN::Dictionary, isa_proxy, 4,
                  sizeof(::THnD_KIN) );
      instance.SetNew(&new_THnD_KIN);
      instance.SetNewArray(&newArray_THnD_KIN);
      instance.SetDelete(&delete_THnD_KIN);
      instance.SetDeleteArray(&deleteArray_THnD_KIN);
      instance.SetDestructor(&destruct_THnD_KIN);
      instance.SetMerge(&merge_THnD_KIN);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::THnD_KIN*)
   {
      return GenerateInitInstanceLocal((::THnD_KIN*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::THnD_KIN*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr THnD_KIN::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *THnD_KIN::Class_Name()
{
   return "THnD_KIN";
}

//______________________________________________________________________________
const char *THnD_KIN::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::THnD_KIN*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THnD_KIN::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::THnD_KIN*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THnD_KIN::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::THnD_KIN*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THnD_KIN::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::THnD_KIN*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void THnD_KIN::Streamer(TBuffer &R__b)
{
   // Stream an object of class THnD_KIN.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(THnD_KIN::Class(),this);
   } else {
      R__b.WriteClassBuffer(THnD_KIN::Class(),this);
   }
}

//______________________________________________________________________________
void THnD_KIN::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class THnD_KIN.
      TClass *R__cl = ::THnD_KIN::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bin", &bin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x[4]", x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*weight_ptr", &weight_ptr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*val_ptrs[4]", &val_ptrs);
      THnT<double>::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_THnD_KIN(void *p) {
      return  p ? new(p) ::THnD_KIN : new ::THnD_KIN;
   }
   static void *newArray_THnD_KIN(Long_t nElements, void *p) {
      return p ? new(p) ::THnD_KIN[nElements] : new ::THnD_KIN[nElements];
   }
   // Wrapper around operator delete
   static void delete_THnD_KIN(void *p) {
      delete ((::THnD_KIN*)p);
   }
   static void deleteArray_THnD_KIN(void *p) {
      delete [] ((::THnD_KIN*)p);
   }
   static void destruct_THnD_KIN(void *p) {
      typedef ::THnD_KIN current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around the merge function.
   static Long64_t  merge_THnD_KIN(void *obj,TCollection *coll,TFileMergeInfo *) {
      return ((::THnD_KIN*)obj)->Merge(coll);
   }
} // end of namespace ROOTDict for class ::THnD_KIN

/********************************************************
* KinFileDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableKinFileDict();

extern "C" void G__set_cpp_environmentKinFileDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("KinFile.h");
  G__cpp_reset_tagtableKinFileDict();
}
#include <new>
extern "C" int G__cpp_dllrevKinFileDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THnD_KIN */
static int G__KinFileDict_628_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   THnD_KIN* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THnD_KIN[n];
     } else {
       p = new((void*) gvp) THnD_KIN[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THnD_KIN;
     } else {
       p = new((void*) gvp) THnD_KIN;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   THnD_KIN* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THnD_KIN(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
     } else {
       p = new((void*) gvp) THnD_KIN(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THnD_KIN(*((TString*) G__int(libp->para[0])));
     } else {
       p = new((void*) gvp) THnD_KIN(*((TString*) G__int(libp->para[0])));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THnD_KIN*) G__getstructoffset())->Fill();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((THnD_KIN*) G__getstructoffset())->GetBinContent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((THnD_KIN*) G__getstructoffset())->ComputeIntegral());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((THnD_KIN*) G__getstructoffset())->Integral());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THnD_KIN*) G__getstructoffset())->updateBin();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((THnD_KIN*) G__getstructoffset())->isOutlayer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THnD_KIN*) G__getstructoffset())->CopyPointers((THnD_KIN*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) THnD_KIN::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THnD_KIN::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) THnD_KIN::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      THnD_KIN::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THnD_KIN*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THnD_KIN::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) THnD_KIN::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THnD_KIN::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KinFileDict_628_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) THnD_KIN::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THnD_KIN G__TTHnD_KIN;
static int G__KinFileDict_628_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (THnD_KIN*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((THnD_KIN*) (soff+(sizeof(THnD_KIN)*i)))->~G__TTHnD_KIN();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (THnD_KIN*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((THnD_KIN*) (soff))->~G__TTHnD_KIN();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THnD_KIN */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncKinFileDict {
 public:
  G__Sizep2memfuncKinFileDict(): p(&G__Sizep2memfuncKinFileDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncKinFileDict::*p)();
};

size_t G__get_sizep2memfuncKinFileDict()
{
  G__Sizep2memfuncKinFileDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceKinFileDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN))) {
     THnD_KIN *G__Lderived;
     G__Lderived=(THnD_KIN*)0x1000;
     {
       THnT<double> *G__Lpbase=(THnT<double>*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN),G__get_linked_tagnum(&G__KinFileDictLN_THnTlEdoublegR),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       THn *G__Lpbase=(THn*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN),G__get_linked_tagnum(&G__KinFileDictLN_THn),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       THnBase *G__Lpbase=(THnBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN),G__get_linked_tagnum(&G__KinFileDictLN_THnBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN),G__get_linked_tagnum(&G__KinFileDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN),G__get_linked_tagnum(&G__KinFileDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableKinFileDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TNDArrayT<Double_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_TNDArrayTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Float_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Double_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Char_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlEchargR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Short_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlEshortgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Int_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlEintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Long_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlElonggR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("THnT<Long64_t>",117,G__get_linked_tagnum(&G__KinFileDictLN_THnTlElongsPlonggR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLorentzVector>",117,G__get_linked_tagnum(&G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KinFileDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THnD_KIN */
static void G__setup_memvarTHnD_KIN(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN));
   { THnD_KIN *p; p=(THnD_KIN*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->bin)-(long)(p)),105,0,0,-1,-1,-1,1,"bin=",0,"current bin index");
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),100,0,0,-1,-1,-1,1,"x[4]=",0,"array of current values (needed for passing to THn)");
   G__memvar_setup((void*)((long)(&p->weight_ptr)-(long)(p)),68,0,0,-1,G__defined_typename("Double_t"),-1,1,"weight_ptr=",0,"! pointer to event weight (need to copy it by hand)");
   G__memvar_setup((void*)((long)(&p->val_ptrs)-(long)(p)),68,0,0,-1,G__defined_typename("Double_t"),-1,1,"val_ptrs[4]=",0,"! array of pointers to variables (need to copy it by hand)");
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(4096).Format("kin_dim=%lldLL",(long long)THnD_KIN::kin_dim).data(),0,"/< Number of variables");
   G__memvar_setup((void*)(&THnD_KIN::kin_nbins),105,0,1,-1,-1,-2,1,"kin_nbins[]=",0,"/< Number of bins per each ");
   G__memvar_setup((void*)(&THnD_KIN::var_name_1),67,0,1,-1,-1,-2,1,"var_name_1=",0,"/< Title of axis of variable 1");
   G__memvar_setup((void*)(&THnD_KIN::var_name_2),67,0,1,-1,-1,-2,1,"var_name_2=",0,"/< Title of axis of variable 2");
   G__memvar_setup((void*)(&THnD_KIN::var_name_3),67,0,1,-1,-1,-2,1,"var_name_3=",0,"/< Title of axis of variable 3");
   G__memvar_setup((void*)(&THnD_KIN::var_name_4),67,0,1,-1,-1,-2,1,"var_name_4=",0,"/< Title of axis of variable 4");
   G__memvar_setup((void*)(&THnD_KIN::bin_edges_1),100,0,1,-1,-1,-2,1,"bin_edges_1[]=",0,"/< Bin edges of variable 1");
   G__memvar_setup((void*)(&THnD_KIN::bin_edges_2),100,0,1,-1,-1,-2,1,"bin_edges_2[]=",0,"/< Bin edges of variable 2");
   G__memvar_setup((void*)(&THnD_KIN::bin_edges_3),100,0,1,-1,-1,-2,1,"bin_edges_3[]=",0,"/< Bin edges of variable 3");
   G__memvar_setup((void*)(&THnD_KIN::bin_edges_4),100,0,1,-1,-1,-2,1,"bin_edges_4[]=",0,"/< Bin edges of variable 4");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__KinFileDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarKinFileDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHnD_KIN(void) {
   /* THnD_KIN */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN));
   G__memfunc_setup("THnD_KIN",655,G__KinFileDict_628_0_1, 105, G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("THnD_KIN",655,G__KinFileDict_628_0_2, 105, G__get_linked_tagnum(&G__KinFileDictLN_THnD_KIN), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - name u 'TString' - 0 '\"\"' title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Fill",391,G__KinFileDict_628_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBinContent",1300,G__KinFileDict_628_0_4, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ComputeIntegral",1555,G__KinFileDict_628_0_5, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Integral",822,G__KinFileDict_628_0_6, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("updateBin",924,G__KinFileDict_628_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isOutlayer",1073,G__KinFileDict_628_0_8, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CopyPointers",1263,G__KinFileDict_628_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'THnD_KIN' - 10 - from", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__KinFileDict_628_0_10, 85, G__get_linked_tagnum(&G__KinFileDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&THnD_KIN::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__KinFileDict_628_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THnD_KIN::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__KinFileDict_628_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&THnD_KIN::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__KinFileDict_628_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&THnD_KIN::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__KinFileDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__KinFileDict_628_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__KinFileDict_628_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THnD_KIN::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__KinFileDict_628_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&THnD_KIN::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__KinFileDict_628_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THnD_KIN::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__KinFileDict_628_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&THnD_KIN::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~THnD_KIN", 781, G__KinFileDict_628_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncKinFileDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalKinFileDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcKinFileDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__KinFileDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnBase = { "THnBase" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THn = { "THn" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_TNDArrayTlEdoublegR = { "TNDArrayT<double>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlEfloatgR = { "THnT<float>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlEdoublegR = { "THnT<double>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlEchargR = { "THnT<char>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlEshortgR = { "THnT<short>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlEintgR = { "THnT<int>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlElonggR = { "THnT<long>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnTlElongsPlonggR = { "THnT<long long>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR = { "vector<TLorentzVector,allocator<TLorentzVector> >" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLorentzVector,allocator<TLorentzVector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KinFileDictLN_THnD_KIN = { "THnD_KIN" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableKinFileDict() {
  G__KinFileDictLN_TClass.tagnum = -1 ;
  G__KinFileDictLN_TBuffer.tagnum = -1 ;
  G__KinFileDictLN_TMemberInspector.tagnum = -1 ;
  G__KinFileDictLN_TObject.tagnum = -1 ;
  G__KinFileDictLN_TNamed.tagnum = -1 ;
  G__KinFileDictLN_TString.tagnum = -1 ;
  G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__KinFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__KinFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__KinFileDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__KinFileDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_THnBase.tagnum = -1 ;
  G__KinFileDictLN_THn.tagnum = -1 ;
  G__KinFileDictLN_TNDArrayTlEdoublegR.tagnum = -1 ;
  G__KinFileDictLN_THnTlEfloatgR.tagnum = -1 ;
  G__KinFileDictLN_THnTlEdoublegR.tagnum = -1 ;
  G__KinFileDictLN_THnTlEchargR.tagnum = -1 ;
  G__KinFileDictLN_THnTlEshortgR.tagnum = -1 ;
  G__KinFileDictLN_THnTlEintgR.tagnum = -1 ;
  G__KinFileDictLN_THnTlElonggR.tagnum = -1 ;
  G__KinFileDictLN_THnTlElongsPlonggR.tagnum = -1 ;
  G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR.tagnum = -1 ;
  G__KinFileDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__KinFileDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KinFileDictLN_THnD_KIN.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableKinFileDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TString);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnBase);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THn);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_TNDArrayTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlEchargR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlEshortgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlEintgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlElonggR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnTlElongsPlonggR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__KinFileDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__KinFileDictLN_THnD_KIN),sizeof(THnD_KIN),-1,324864,(char*)NULL,G__setup_memvarTHnD_KIN,G__setup_memfuncTHnD_KIN);
}
extern "C" void G__cpp_setupKinFileDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupKinFileDict()");
  G__set_cpp_environmentKinFileDict();
  G__cpp_setup_tagtableKinFileDict();

  G__cpp_setup_inheritanceKinFileDict();

  G__cpp_setup_typetableKinFileDict();

  G__cpp_setup_memvarKinFileDict();

  G__cpp_setup_memfuncKinFileDict();
  G__cpp_setup_globalKinFileDict();
  G__cpp_setup_funcKinFileDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncKinFileDict();
  return;
}
class G__cpp_setup_initKinFileDict {
  public:
    G__cpp_setup_initKinFileDict() { G__add_setup_func("KinFileDict",(G__incsetup)(&G__cpp_setupKinFileDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initKinFileDict() { G__remove_setup_func("KinFileDict"); }
};
G__cpp_setup_initKinFileDict G__cpp_setup_initializerKinFileDict;

