/********************************************************************
* KinFileDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error KinFileDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableKinFileDict();
extern void G__cpp_setup_inheritanceKinFileDict();
extern void G__cpp_setup_typetableKinFileDict();
extern void G__cpp_setup_memvarKinFileDict();
extern void G__cpp_setup_globalKinFileDict();
extern void G__cpp_setup_memfuncKinFileDict();
extern void G__cpp_setup_funcKinFileDict();
extern void G__set_cpp_environmentKinFileDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KinFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__KinFileDictLN_TClass;
extern G__linked_taginfo G__KinFileDictLN_TBuffer;
extern G__linked_taginfo G__KinFileDictLN_TMemberInspector;
extern G__linked_taginfo G__KinFileDictLN_TObject;
extern G__linked_taginfo G__KinFileDictLN_TNamed;
extern G__linked_taginfo G__KinFileDictLN_TString;
extern G__linked_taginfo G__KinFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KinFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KinFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__KinFileDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__KinFileDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__KinFileDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_THnBase;
extern G__linked_taginfo G__KinFileDictLN_THn;
extern G__linked_taginfo G__KinFileDictLN_TNDArrayTlEdoublegR;
extern G__linked_taginfo G__KinFileDictLN_THnTlEfloatgR;
extern G__linked_taginfo G__KinFileDictLN_THnTlEdoublegR;
extern G__linked_taginfo G__KinFileDictLN_THnTlEchargR;
extern G__linked_taginfo G__KinFileDictLN_THnTlEshortgR;
extern G__linked_taginfo G__KinFileDictLN_THnTlEintgR;
extern G__linked_taginfo G__KinFileDictLN_THnTlElonggR;
extern G__linked_taginfo G__KinFileDictLN_THnTlElongsPlonggR;
extern G__linked_taginfo G__KinFileDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR;
extern G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KinFileDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__KinFileDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KinFileDictLN_THnD_KIN;

/* STUB derived class for protected member access */
